name: AndroidBuildAPK
on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v2  # Updated version
        with:
          java-version: '17'
          distribution: 'adopt'  # Corrected the parameter name

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2  # Updated version
        with:
          name: MyAndroidAPK
          path: app/build/outputs/apk/debug/app-debug.apk
